### ISSUE TITLE
Geocode Plants and Coops

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-intranet#25]
Da man die Breiten/Längengrade nicht mehr bearbeiten kann -> Geocoder

**Comment by liebhock** [comment]
Als Redakteur kann bei "Neue Anlage hinzufügen" keine neue Anlage ergänzt werden.
https://portal.buergerwerke.de/cooperatives/3/plants

>>submit --> "Breitengrad ist keine Zahl" + "Längengrad ist keine Zahl" 
Aber das Formular enthält keine Felder für Orts- oder Adressangabe.

**Comment by liebhock** [comment]
In der Map (http://intranet.buergerwerke.de/cooperatives) werden aktuell die Marker für die Mitglieder nicht angezeigt. --> bitte prüfen, wenn geocodes wieder funktionieren sollten hier auch die Marker auftauchen.
