### ISSUE TITLE
Upload Function Active Admin

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-intranet#3]
Upload-Funktion für Cooperatives, Members, Plants. 

CSV-Import

**Comment by liebhock** [comment]
Isa: 
Mitgliederlisten Import funktioniert noch nicht > sollte das schon gehen? Hier wäre auch zu beachten/besprechen ob ein Upload die bestehenden Einträge ergänzt oder ersetzt... bzw. am besten wäre wahrscheinlich auf Namen zu prüfen und bestehende updaten und nicht bestehende anlegen=> aber dann wäre wichtig zu beachten, dass Änderungen der Genossenschaften ggf. überschrieben werden (Klären, was die aktuellste Version sein soll?)

**Comment by morris-frank** [comment]
Import funktioniert jetzt für BEGs, dank 9bcca8b125eee6b3a7e87b9851eb8c5325a92019, Überschreiben-Funktion fehlt noch.
