### ISSUE TITLE
Mailer template / Benutzer-Einladung fixen

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-intranet#52]
Es fehlt ein template für den Mailer der von Devise benutzt wird...

**Comment by liebhock** [comment]
1) Übersetzung des Mail-Textes
2) Nach Klick auf Link in E-Mail 
http://intranet.buergerwerke.de/members/invitation/accept?invitation_token=xxxxxxxxxxx
und Passwort-Eingabe: Fehlermeldung auf http://intranet.buergerwerke.de/members/invitation 
--> "Incomplete response received from application" (nicht auf Standard-Fehlerseite (Nur Text)

**Comment by morris-frank** [comment]
Kann ich nicht reproduzieren :confused: 

Bei mir geht es. Nach der Passworteingabe werde ich direkt eingeloggt und auf die Startseite geleitet.
