### ISSUE TITLE
Admin Customer Data: Accept single CSV and PDF files

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-intranet#54]
Right now the Adminpanel Code for the customer data only accepts ZIP files (so also single csv e.g. have to inside a zip file).

It would be better UX with single PDF and CSV files were also supported.

**Comment by liebhock** [comment]
addition:
a zip-file with a single .csv-file is also not accepted. 
Errormessage: "Sie haben keine ZIP Datei hochgeladen." 
--> Für Dokumentation: Anforderungen an Datei/Verzeichnis-Benennung bzw. csv-layout dokumentieren/transparent machen.

**Comment by liebhock** [comment]
only zip is ok, since rarely single files will be uploaded
