### ISSUE TITLE
"Benutzer ändern"-Button funktioniert nicht als user 

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#58]
Als Redakteur kann ich hier
http://intranet.buergerwerke.de/cooperatives/3/members
die Benutzer der HEG einsehen. Häckchen kann ich setzen und löschen + Button "Ändern" ist sichtbar - aber ist nicht anklickbar.

**Comment by morris-frank** [comment]
Kann ich nicht reproduzieren.

Der Button ist auch eigentlich nur als BEG _Admin_ sichtbar.

**Comment by liebhock** [comment]
richtig, bin auch als BEG-Admin eingeloggt gewesen. Kannst du als BEG-Admin z.B. für HEG dort Haken ändern und die Änderungen über den Button speichern?

**Comment by liebhock** [comment]
getrennt aufnehmen oder hier mit rein?
Zusätzlich als im admin-panel kann ich einen Benutzer nur bearbeiten, also bspw. das Häckchen als Vorstand entfernen, wenn ich dann auch sein Passwort eingebe.

**Comment by morris-frank** [comment]
Das mit dem Passwort liegt daran, dass man momentan Benutzer einfach einträgt und nicht einlädt wie später. Ich ändere das mal.

**Comment by morris-frank** [comment]
wurde auch durch 79082ede326bfd08d323c9ffa62ab04b7487def7.

Formulare innerhalb von Tabellen sind wohl nicht so einfach...
