### ISSUE TITLE
Fehlerseite Umleitung oder bessere Fehlermeldung

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#60]
Bei nicht-existenten Seiten, wie bspw.
http://intranet.buergerwerke.de/cooperatives/6 (aktuell sind nur 2 Genossenschaften angelegt) heißt es einfach:
The page you were looking for doesn't exist. --> zumindest ein Button oder eine automatische Weiterleitung zur Startseite nach 2 Sekunden wäre gut.

**Comment by morris-frank** [comment]
Ist jetzt programmatisch gelöst durch ec9fcea791ff28ae14eff242bf1ae860a65822df und f38c2652796ad02e79caa6c24d6d2288d7af5eb1.
