### ISSUE TITLE
Passwort setzen Formular designen

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-intranet#63]
Wenn ich mein Passwort als Benutzer vergebe nachdem ich eingeladen wurde, sehe ich ein noch nicht designtes Formular.

Wo auch immer das herkommt, es muss angepasst werden.

**Comment by liebhock** [comment]
Link zum Formular: 
http://intranet.buergerwerke.de/members/invitation/accept?invitation_token=xxxxxxxxxxxxxxx

Anleitung: 
https://github.com/scambra/devise_invitable/wiki/How-To:-Allow-updating-additional-attributes-when-accepting-invitation
