### ISSUE TITLE
make buttons for selected rows of customer-data functional (in chrome-browser)

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#79]
Aktuell sind bei den Buttons die ersten 5 ausgewählt, es werden aber alle Spalten angezeigt in der tabellarischen Übersicht.
Die Buttons haben noch keine Funktion/Auswirkung auf die Darstellung der Tabelle.

**Comment by morris-frank** [comment]
Seltsam... Bei mir auf dem Laptop geht alles, und jetzt auf meinem Smartphone gehen zwar die buttons nicht aber zumindest werden nur die ersten 5 angezeigt.. Wahrscheinlich Browser Inkompatibilität

**Comment by liebhock** [comment]
#79 mit win10 64 + chrome (beide fully updated) festgestellt. -Aktualisiere hier, wenn ich Fehler besser eingrenzen kann.

**Comment by liebhock** [comment]
Browser-Inkompatibilität kann ich bestätigen.
Feature funktioniert jetzt wie erwartet in FF, nachdem Scripte (NoScript Plugin) erlaubt sind wie erlaubt sind - abgesehen von #88 
In Chrome kann der bug reproduzuiert werden - in der Produktionsumgebung sind in der Spaltenauswahl die ersten fünf markiert, aber es lassen sich keine weiteren auswählen, alle Spalten werden in der Tabelle angezeigt. Mouseover zeigt, dass es Buttons sind. -> F5 -> In Spaltenauswahl können nun Spalten markiert und abgewählt werden. Aber es werden immer alle Spalten angezeigt, keine Auswirkung auf die angezeigten Spalten in der Tabelle.

Anpassung der Spaltenbreite nehme ich als getrenntes Issue auf.

**Comment by liebhock** [comment]
In Edge funktioniert es wie in Firefox - die Spaltenauswahl wird in der Tabelle reflektiert. Ein Reload ist auch hier notwendig.
