### ISSUE TITLE
let user choose how many lines are displayed + pagination 

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#80]
![image](https://user-images.githubusercontent.com/40856339/43540556-585afc58-95c8-11e8-827a-dd3debcce75b.png)

So könnte das aussehen?

**Comment by morris-frank** [comment]
BEG haben jetzt Seiten in den Listen, Anzahl pro Seite momentan Fix, Suche nur auf die aktuelle Seite beschränkt!

**Comment by liebhock** [comment]
> Suche nur auf die aktuelle Seite beschränkt!
Das schränkt die usability des Filters natürlich massiv ein. 
issue bitte offen lassen, bis wir eine gute Navigation durch 200+ Kundendaten  ermöglicht haben.

**Comment by morris-frank** [comment]
Momentan ist pageination auch nur für die BEG Liste aktiviert, die Kundendaten sind einer Langen Liste.

Das die Suche durch alle Seiten gehen soll ist natürlich richtig. Das ist dann nochmal bedeutent komplizierter..

**Comment by liebhock** [comment]
pagination für BEG Liste ist gut.

**Comment by morris-frank** [comment]
#99
