### ISSUE TITLE
Menu entries in header (mobile device) not accessible (function)

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#81]
In mobilder Ansicht führt das Mouse-over dazu, dass das kleine Menü-Symbol verschwindet, sobald es hervorgehoben wird.
![image](https://user-images.githubusercontent.com/40856339/43663299-47dec5f6-9769-11e8-8be7-25a3d2169023.png)

**Comment by liebhock** [comment]
Funktion wie im Issue beschrieben ist gefixed, aber jetzt lässt sich das Menü nicht mehr über das Icon öffnen.

**Comment by morris-frank** [comment]
Welcher Browser?

**Comment by liebhock** [comment]
chrome ist betroffen
FF funktioniert. :)

**Comment by morris-frank** [comment]
Problem besteht nicht mehr
