### ISSUE TITLE
replace deprecated ruby sass? (2019)

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#83]
Post-install message from sass:
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811

Question - is this the same "sass-rails" used for this application and the message valid for our app?

**Comment by morris-frank** [comment]
https://github.com/rails/sass-rails/issues/420

**Comment by morris-frank** [comment]
Sieht so aus als muss sich auch Rails erstmal darum kümmern

**Comment by morris-frank** [comment]
Sassc-rails muss kompiliert werden (eine Gem extension) -> muss auf Artfiles erst installiert werden vor dem nächsten update in production...
