### ISSUE TITLE
move from sqlite3 to mysql database for production system

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#84]
please evaluate - with more data and users mysql could have performance benefits over sqlite3, correct?

**Comment by morris-frank** [comment]
SQLite hat einen großen Nachteil. Schreiboperationen können nicht parallel ausgeführt werden. Das ist nur ein Problem, bei Produktionsumgebungen bei denen viel geschrieben wird -> das ist hier eigentlich nicht der Fall (viele Änderungen bei DBs heißt tausende Operationen in der Minute oder sowas...)

Ich denke die Vorteile von MySQL oder PostGres sind in diesem Fall nur theoretisch...
