### ISSUE TITLE
column-chooser functions only on reload

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#88]
An zwei Stellen Spaltenauswahl für Kundendaten (vgl. #79) und Anzeige des Tarifrechners (#82) funktioniert die Oberfläche in der Produktionsumgebung erst nach einem Reload (F5) so, wie erwartet. Beobachtet in FF und Chrome und Edge.
1) Tarifrechner hat Scrollbalken - nach reload funktioniert das autoresize-feature einwandfrei: ![image](https://user-images.githubusercontent.com/40856339/43756323-600d0e0a-9a14-11e8-9712-1d3af4906b22.png)

2) Spaltenauswahl über Kundendatentabelle reagiert nicht auf Mausklick - nach reload funktioniert das Auswahl-feature wie erwartet (jedenfalls in FF - vgl. #79)

**Comment by morris-frank** [comment]
Der Taca-Teil sollte jetzt gehen, bitte testen! Habe die Duplikat Issues mal geschlossen.

**Comment by morris-frank** [comment]
Letzter commit sollte auch Kundendatentabelle fixen -> bitte testen

**Comment by liebhock** [comment]
Leider ist Funktionalität bei mir unverändert. s. obige Fehlerbeschreibung. (cache, cookies gelöscht)
Der Unterschied zwischen Chrome und FF bei Kundendaten ist: FF ändert die angezeigten Tabellenspalten, Chrome zeigt immer alle an.

**Comment by morris-frank** [comment]
Der Commit ist noch nicht in production, weil erst noch eine gem extension installiert werden musste..

**Comment by liebhock** [comment]
Nice! :)
Taca-autosize funktioniert jetzt sofort, sowohl in chrome, als auch FF.
Kundendaten-Spaltenauswahl funktioniert jetzt grundsätzlich auch in Chrome!

Allerdings ist in Chrome und FF für die Funktionsfähigkeit der Buttons weiterhin ein Reload notwendig.

**Comment by morris-frank** [comment]
ja ist mir gerade in chrome auch wieder aufgefallen... das kann doch echt nicht so schwierig sein :astonished:
