### ISSUE TITLE
reorder Filter and legend above customer-data table

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#89]

**Comment by liebhock** [comment]
ergänze eine Legende für die Spaltentitel.

**Comment by morris-frank** [comment]
Legende hinzugefügt in d6c6139cea0e5129076c7cfb544ede7f4d4c1000

Muss nur ausgefüllt werden

**Comment by morris-frank** [comment]
fix cd407249da105e8a68d720b66878cc6772fa6e71
