### ISSUE TITLE
make column-heading sticky for customer-data (usability)

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#91]
Die Spaltenüberschriften sollten immer sichtbar sein, auch wenn in den Kundendaten viele Zeilen angezeigt werden und man ganz herunterscrollt.

**Comment by morris-frank** [comment]
Vergleiche mit https://stackoverflow.com/questions/43909940/why-does-overflowhidden-prevent-positionsticky-from-working -> deswegen hat table-container besser eine feste Höhe
