### ISSUE TITLE
improve error message or autocorrect geno-website (admin-panel)

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#93]
Im csv-upload für Genos wird eine Webseite im Format "genossenschaft.de" akzeptiert. 
Wenn die BEG im admin panel bearbeitet wird, kommt die Fehlermeldung für das Website-Feld: "ist nicht gültig" -> muss auf die Form "https://genossenschaft.de" korrigiert werden.

**Comment by morris-frank** [comment]
Ja für die Imports ist Validation komplett ausgestellt, ist glaube ich einfacher, sonst werden da bei den kleinsten Fehlern der import nicht akzeptiert. Aber ja die Fehlermeldung kann mna noch anpassung
