### ISSUE TITLE
add customer-data analytics in customer-data view

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#94]
Aus den verfügbaren Kundendaten je BEG Kenndaten bilden. (vgl. bisherige Informationspolitik - wichtige Analysen/Kenndaten müssen erhalten bleiben.

* Ist es möglich über alle in der db abgelegten Kundendaten Aggregate zu bilden und diese wiederum als Rechengrundlage in allen BEG-Bereichen verfügbar zu haben? (globale Variable? = benchmarks)
* Übersicht über die TOP5 des jeweilig letzten Monats

**Comment by morris-frank** [comment]
Was für Aggregate sind genau gemeint?
