### ISSUE TITLE
improve seeds content (dev-env)

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-intranet#96]
Der Seeds-Umfang, Inhalt/Diversität sollte für effektives Testen der Features verbessert werden.
==> Ein Set/Datensatz definieren, mit allen Ausprägungen, die es geben sollte. 

* Member (CHECK)
** alle Rollen abdecken - Rolle in email ersichtlich machen. (TODO)
** über mehrere Genos verteilen (CHECK)

* Genos (CHECK)
** mit / ohne Tarif (TODO)

* Kategorien (CHECK)
** einige, auch verschachtelte Testkategorien anlegen (TODO)

* Dateien (TODO)
** geht das mit seeds überhaupt? -> Verzeichnis mit zip-Dateien anlegen, die dann nach Initialisierung automatisch in den Zip-Upload kommen?
** Zugriffsberechtigungen abdecken (all, tariff, specific) (TODO)
** Dateien über einige Kategorien verteilen (TODO)

* Anlagen (CHECK)
** alle Typen (TODO)

* Kundendaten (TODO)
** vgl. Dateien oder direkt in db aufnehmen. (?)
** KD mit/ohne Zustimmung; rlm/slp; firma/privat; in Belieferung/im Wechsel/gekündigt; untersch. Tarif-IDs; 
** KD für mehrere Genos - geringe/größere Anzahl

* KD-Diagramme (Bilder/pdf)
** Dateityp abhängig von #95, wenn Grafiken --> 2-3 in einer Geno

Fehlt noch was?

**Comment by morris-frank** [comment]
Dateien in den Seeds anhängen ist machbar, aber weiß nicht ob ich die dann ins Git-Repo laden würde. Vielleicht ist es besser einfach ein ZIP zur verfügung zu stellen.

**Comment by liebhock** [comment]
richtig, ins git-repo sollten die nicht.

**Comment by morris-frank** [comment]
Bis auch die Kundendaten ist alles drin
